config/routes.rb
Rails.application.routes.draw do
  resources :comments

  namespace :api do
    resources :comments
  end

  root to: "comments#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    comments = Comment.all

    render json: comments
  end

  def show
    comment = Comment.find(params[:id])

    render json: comment
  end

  def create
    comment = Comment.new(comment_params)

    if comment.save
      render json: comment
    else
      render json: comment.errors.full_messages, status: :unprocessable_entity
    end
  end

  def update
    comment = Comment.find(params[:id])

    if comment.update(comment_params)
      render json: comment
    else
      render json: comment.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy

    render json: comment
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
    render :index
  end

  def show
    @comment = Comment.find(params[:id])
    render :show
  end

  def new
    @comment = Comment.new
    render :new
  end

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to comments_url
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    render :edit
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to comment_url(@comment)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to comments_url
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<% if flash[:errors] %>
<ol class="errors">
<% flash[:errors].each do |error| %>
  <li><%= error %></li>
<% end %>
</ol>
<% end %>

<form class="other" action="<%= comment_url(@comment) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="put">

  <div>
    <label for="comment_body">Body</label>
    <textarea name="comment[body]"><%= @comment.body %></textarea>
  </div>

  <button>Submit</button>
</form>

app/views/comments/index.html.erb
<h1>Conz's Cool Comments</h1>
<a href="<%= new_comment_url %>">Add a new comment</a>

<ul>
  <% @comments.each do |comment| %>
  <li><a href="<%= comment_url(comment) %>"><%= comment.body %></a></li>
  <% end %>
</ul>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<% if flash[:errors] %>
<ol class="errors">
<% flash[:errors].each do |error| %>
  <li><%= error %></li>
<% end %>
</ol>
<% end %>

<form class="other" action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <div>
    <label for="comment_body">Body</label>
    <textarea id="comment_body" name="comment[body]"><%= @comment.body %></textarea>
  </div>

  <button>Submit</button>
</form>

app/views/comments/show.html.erb
<p><%= @comment.body %></p>

<nav>
  <a href="<%= comments_url %>">Back to all comments</a>

  <a href="<%= edit_comment_url(@comment) %>">Edit comment</a>

  <form class="destroy" action="<%= comment_url(@comment) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="delete">

    <button>Delete comment????</button>
  </form>
</nav>

<figure class="cool">
  <figcaption>Cool comment, Conz!</figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoolConz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>